apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: mail-worker
  name: mail-worker
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: mail-worker
  template: 
    metadata: 
      labels: 
        app: mail-worker
    spec: 
      containers: 
        - 
          env: 
            - 
              name: TOPIC_NAME
              value: "mail_topic"
            - 
              name: KAFKA_BROKER
              value: "10.102.253.114:9092"
            - 
              name: CONSUMER_GROUP
              value: "mail_group"
      
          image: "ncbunty/mail-worker"
          name: mail-worker
